# Uncomment this line to define a global platform for your project
platform :ios, ‘9.0’
# Uncomment this line if you're using Swift
use_frameworks!

target 'PeopleCongressSystemxg' do

pod 'TagListView', '~> 1.0.0'
pod 'EZLoadingActivity', '~> 0.8'
pod 'Alamofire'
pod 'HUIPatternLockView-Swift'
pod 'GrowingTextView'
pod 'AlamofireImage'
pod 'SwiftQRCode'
pod 'ReachabilitySwift'
pod 'DKImagePickerController'

end

