# Uncomment this line to define a global platform for your project
platform :ios, ‘8.0’
# Uncomment this line if you're using Swift
use_frameworks!

target 'PeopleCongressSystem' do

pod 'Alamofire'
pod 'HUIPatternLockView-Swift'
pod 'TagListView'
pod 'EZLoadingActivity', '~> 0.8'
pod 'GrowingTextView'
pod 'SDWebImage'

end

